-- @description Various Actions for conditional Track-selecting
-- @version 1.02
-- @author Joshnt
-- @changelog
--  + init
-- @metapackage
-- @provides
--   [main] joshnt_Select Tracks/joshnt_Select Tracks of items in region at edit cursor.lua
--   [main] joshnt_Select Tracks/joshnt_Select Tracks of items in selected region.lua