-- @description Move sel. items to cursor
-- @version 1.0
-- @author Joshnt
-- @about
--      Moves items to the selected track - offers other actions to keep relative position between selected items
-- @changelog
--  + init - Thanks to McWolverine for the idea!
-- @metapackage
-- @provides
--   [main] joshnt_Move selected item(s) to cursor/joshnt_Move selected item(s) to mouse cursor.lua
--   [main] joshnt_Move selected item(s) to cursor/joshnt_Move selected item(s) to mouse cursor - keep relative position (time).lua
--   [main] joshnt_Move selected item(s) to cursor/joshnt_Move selected item(s) to mouse cursor - keep relative position (time+tracks).lua
