-- @description Move sel. items to cursor
-- @version 1.1
-- @author Joshnt
-- @about
--      Moves items to the selected track - offers other actions to keep relative position between selected items
-- @changelog
--  - added "... - only time" and "... - only track" variants
-- @metapackage
-- @provides
--   [main] joshnt_Move selected item(s) to cursor/joshnt_Move selected item(s) to mouse cursor.lua
--   [main] joshnt_Move selected item(s) to cursor/joshnt_Move selected item(s) to mouse cursor - keep relative position (time).lua
--   [main] joshnt_Move selected item(s) to cursor/joshnt_Move selected item(s) to mouse cursor - keep relative position (time+tracks).lua
--   [main] joshnt_Move selected item(s) to cursor/joshnt_Move selected item(s) to track under mouse cursor - keep position.lua
--   [main] joshnt_Move selected item(s) to cursor/joshnt_Move selected item(s) to position under mouse cursor - keep track.lua
