-- @description Fade Utility
-- @version 1.02
-- @author Joshnt
-- @about
--      Multiple single actions for creating fades
-- @changelog
--  + init
-- @metapackage
-- @provides
--   [main] joshnt_Fade Utility/joshnt_Set minimal fade-in and -out for selected items if no fade.lua
--   [main] joshnt_Fade Utility/joshnt_Toggle change selected items fade to S- or Log-Shape (fade in or out depending on mouse position).lua
--   [main] joshnt_Fade Utility/joshnt_Trim left edge of selected item(s) to edit cursor without changing fade-in end.lua
--   [main] joshnt_Fade Utility/joshnt_Trim right edge of selected item(s) to edit cursor without changing fade-out start.lua