-- @description Zoom to overlapping item group at cursor
-- @version 1.01
-- @author Joshnt
-- @about
--    Various actions for zooming/ scrolling to overlapping item group at cursor
-- @changelog
--  + init
-- @metapackage
-- @provides
--   [main] joshnt_Zoom to items/joshnt_Zoom to overlapping items across all tracks at edit cursor.lua
--   [main] joshnt_Zoom to items/joshnt_Zoom to overlapping items across selected tracks at edit cursor.lua