-- @description Zoom to overlapping item group at cursor
-- @version 1.0
-- @author Joshnt
-- @about
--    Various actions for zooming/ scrolling to overlapping item group at cursor
-- @changelog
--  + init
-- @metapackage
-- @provides
--   [main] joshnt_Insert or remove time at start and end of timeselection/joshnt_Insert 1 second time at start and end of time selection.lua
--   [main] joshnt_Insert or remove time at start and end of timeselection/joshnt_Remove 1 second time at start and end of time selection.lua

