-- @description Change Region Length - Package
-- @version 2.0
-- @author Joshnt
-- @changelog
--  - added Set nearest region edges to media item for only most overlapping region
--  - added Set nearest region edges to media item for only most overlapping region - per overlapping item stack
--  - both originally based on acendan script "Set nearest region edges to selected media items"
-- @metapackage
-- @provides
--   [main] joshnt_Change Region Length/joshnt_Change selected region(s) length....lua
--   [main] joshnt_Change Region Length/joshnt_Extend region(s) at edit cursor end by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Extend region(s) at edit cursor start by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Extend selected region(s) end by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Extend selected region(s) start by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Shorten region(s) at edit cursor end by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Shorten region(s) at edit cursor start by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Shorten selected region(s) end by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Shorten selected region(s) start by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt-acendan_Set nearest region edges of most overlapping region to selected media items.lua
--   [main] joshnt_Change Region Length/joshnt-acendan_Set nearest region edges of most overlapping region to selected media items - per overlapping item group.lua