-- @description Various Actions for selecting regions (in the region marker manager)
-- @version 1.01
-- @author Joshnt
-- @changelog
--  + init
-- @metapackage
-- @provides
--   [main] joshnt_Select Regions/joshnt_Invert Region Selection.lua
--   [main] joshnt_Select Regions/joshnt_Select only Region(s) in time selection.lua
--   [main] joshnt_Select Regions/joshnt_Select Region(s) at edit cursor.lua
--   [main] joshnt_Select Regions/joshnt_Select Region(s) in time selection.lua
--   [main] joshnt_Select Regions/joshnt_Select Region(s) overlapping with item selection.lua
--   [main] joshnt_Select Regions/joshnt_Select region(s) with items on same tracks as selected region(s) or region at edit cursor.lua
--   [main] joshnt_Select Regions/joshnt_Select Region(s) with items on selected tracks.lua