-- @description Change Region Length - Package
-- @version 1.0
-- @author Joshnt
-- @changelog
--  + init
-- @metapackage
-- @provides
--   [main] joshnt_Change Region Length/joshnt_Change selected region(s) length....lua
--   [main] joshnt_Change Region Length/joshnt_Extend region(s) at edit cursor end by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Extend region(s) at edit cursor start by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Extend selected region(s) end by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Extend selected region(s) start by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Shorten region(s) at edit cursor end by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Shorten region(s) at edit cursor start by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Shorten selected region(s) end by 1 second.lua
--   [main] joshnt_Change Region Length/joshnt_Shorten selected region(s) start by 1 second.lua