-- @description Various Actions for adding different tracks of regions to the RRM
-- @version 1.01
-- @author Joshnt
-- @changelog
--  + init
-- @metapackage
-- @provides
--   [main] joshnt_Add to Region Render Matrix/joshnt_Add selected Region(s) to region render matrix via highest common parent of items per region.lua
--   [main] joshnt_Add to Region Render Matrix/joshnt_Add selected Region(s) to region render matrix via highest parent(s) or top-level tracks of items per region.lua
--   [main] joshnt_Add to Region Render Matrix/joshnt_Add selected Region(s) to region render matrix via Master.lua
--   [main] joshnt_Add to Region Render Matrix/joshnt_Add selected Region(s) to region render matrix via selected Track(s).lua
--   [main] joshnt_Add to Region Render Matrix/joshnt_Add selected Region(s) to region render matrix via tracks with items in corresponding region.lua
--   [main] joshnt_Add to Region Render Matrix/joshnt_Add selected Track(s) to region render matrix via region(s) with items.lua
--   [main] joshnt_Add to Region Render Matrix/joshnt_Copy region render matrix selection from region at cursor to selected region(s).lua