-- @description Convert Regions into Start End Markers (FMOD Timeline preparation)
-- @version 1.0
-- @author Joshnt
-- @about
--    as the FMOD integration allows for exporting markers but not regions into an FMOD event, I thought it might be useful to have all your regions as markers for potential regions in FMOD.
-- @changelog
--  - init
-- @metapackage
-- @provides
--   [main] joshnt_Convert Regions into Start End Markers (FMOD Timeline preparation)/joshnt_Add Start End Markers to All Regions (FMOD Timeline preparation).lua
--   [main] joshnt_Convert Regions into Start End Markers (FMOD Timeline preparation)/joshnt_Add Start End Markers to Regions in timeselection (FMOD Timeline preparation).lua
--   [main] joshnt_Convert Regions into Start End Markers (FMOD Timeline preparation)/joshnt_Add Start End Markers to selected Regions (FMOD Timeline preparation).lua
--   [main] joshnt_Convert Regions into Start End Markers (FMOD Timeline preparation)/joshnt_Convert All Regions into Start End Markers (FMOD Timeline preparation).lua
--   [main] joshnt_Convert Regions into Start End Markers (FMOD Timeline preparation)/joshnt_Convert Regions in timeselection into Start End Markers (FMOD Timeline preparation).lua
--   [main] joshnt_Convert Regions into Start End Markers (FMOD Timeline preparation)/joshnt_Convert selected Regions into Start End Markers (FMOD Timeline preparation).lua