-- @description Create seamless loop in items
-- @version 2.0.1
-- @changelog
--  - added option to clear manually
-- @author Joshnt
-- @about 
--    ## Create seamless loops in items
--      different sub-scripts
--
--    ## CREDITS TO X-RAYM
--    This is mostly an adaption of X-Raym's script "Script: X-Raym_Create seamless loops from selected items sections inside time selection.lua".
-- @metapackage
-- @provides
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in selected items at timeselection, re-extend and create '#' region over loop.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in selected items, re-extend and create '#' region over loop - use timeselection over first selected item as reference.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in selected items, re-extend and create '#' region over loop - use timeselection over first selected item as reference - single region revert possible.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Revert seamless loop at timeselection - restore on absolute track index.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Revert seamless loop at timeselection - restore on identical track name if possible.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Clear saved item edits for seamless loop (reduce project size).lua
--  [main] joshnt_Create seamless loop in item/joshnt_Save item edits for seamless loop manually.lua
