-- @description Run Action over over items/tracks/time on region (individually per region)
-- @version 1.01
-- @author Joshnt
-- @about
--    Run Action over items/tracks/time on region (individually per region) - script selects items, tracks, time and envelope points per region
--    Usecase e.g. SWS_Set selected items to One Random Custom Color, joshnt_ReaGlue-Regions.lua, ...
-- @changelog
--  + init
-- @metapackage
-- @provides
--   [main] joshnt_Run Actions for items, tracks, time or envelope of region (individually per region)/joshnt_Run Action for items tracks or time in all regions (individually per region).lua
--   [main] joshnt_Run Actions for items, tracks, time or envelope of region (individually per region)/joshnt_Run Action for items tracks or time in regions in time selection (individually per region).lua
--   [main] joshnt_Run Actions for items, tracks, time or envelope of region (individually per region)/joshnt_Run Action for items tracks or time in selected regions (individually per region).lua