-- @description Create seamless loop in items
-- @version 2.1.4
-- @changelog
--  - minor bugfixes
-- @author Joshnt
-- @about 
--    ## Create seamless loops in items
--      different sub-scripts with modifier:
--      - create seamless loop in selected items at time selection, re-extend and create '#' region over loop -> only selected items in time selection will be looped
--      - create seamless loop in selected items at time selection, re-extend and create '#' region over loop - use time selection as reference -> selected items in time selection will be looped and later selected items will be looped according to offset of first item to time selection
--
--    ## CREDITS TO X-RAYM
--    This is mostly an adaption of X-Raym's script "Script: X-Raym_Create seamless loops from selected items sections inside time selection.lua".
-- @metapackage
-- @provides
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in selected items at timeselection, re-extend and create '#' region over loop.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in selected items, re-extend and create '#' region over loop - use timeselection over first selected item as reference.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in selected items, re-extend and create '#' region over loop - use timeselection over first selected item as reference - single region revert possible.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Revert seamless loop at timeselection - restore on absolute track index.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Revert seamless loop at timeselection - restore on identical track name if possible.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Clear saved item edits for seamless loop (reduce project size).lua
--  [main] joshnt_Create seamless loop in item/joshnt_Save item edits for seamless loop manually.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in all items, re-extend and create '#' region over loop - use timeselection over first item as reference - single region revert possible.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in all items, re-extend and create '#' region over loop - use timeselection over first item as reference.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in all items, re-extend and create '#' region over loop (ignore MIDI-items) - use timeselection over first item as reference - single region revert possible.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in all items, re-extend and create '#' region over loop (ignore MIDI-items) - use timeselection over first item as reference.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Revert seamless loop at timeselection (ignore MIDI-items) - restore on absolute track index.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Revert seamless loop at timeselection (ignore MIDI-items) - restore on identical track name if possible.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in all items at timeselection (ignore MIDI-items), re-extend and create '#' region over loop.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in all items at timeselection, re-extend and create '#' region over loop.lua



