-- @description Create seamless loop in items
-- @version 1.1.3
-- @changelog
--  - bugfix on multiselected items (time-select for later items now references time-selection beginning point for both offsets)
--  -> the so called "SwobugHunter" was on duty again
-- @author Joshnt
-- @about 
--    ## Create seamless loops in items
--      different sub-scripts
--
--    ## CREDITS TO X-RAYM
--    This is mostly an adaption of X-Raym's script "Script: X-Raym_Create seamless loops from selected items sections inside time selection.lua".
-- @metapackage
-- @provides
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in selected items at timeselection, re-extend and create '#' region over loop.lua
--  [main] joshnt_Create seamless loop in item/joshnt_Create seamless loop in selected items, re-extend and create '#' region over loop - use timeselection over first selected item as reference.lua
